title = "danielproctor.dev"
languageCode = "en-gb"
copyright = "© Daniel Proctor"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "Europe/London"
theme = ["github.com/nicokaiser/hugo-theme-gallery/v2"]
googleAnalytics = "G-Z0VZZ5WENF"

[params]
  # open graph
  title = "photo.danielproctor.dev"
  description = "Photography by Daniel Proctor"

  defaultTheme = "dark"

[author]
  name = "Daniel Proctor"

[outputs]
  page = ["HTML"]
  home = ["HTML"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"